### ISSUE TITLE
Server auto-update of docker-engine kills login.libris.kb.se services

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#121]
Possible fixes:
* [x] Make Docker containers autostarting; `restart: always`
* [x] Disable auto-update of docker-engine (yum version lock?)

**Comment by mxtthias** [comment]
Add version lock:

```
yum install yum-versionlock
yum versionlock docker-ce
```

We disabled yum-cron temporarily:
```
systemctl disable yum-cron
systemctl stop yum-cron
systemctl status yum-cron
```

**Comment by mblomdahl** [comment]
@mxtthias Re-enabled `yum-cron`!
