### ISSUE TITLE
Ändra "Viktigt!"-box på profilsidan

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#131]
<img width="581" alt="screen shot 2017-12-14 at 11 11 55 am" src="https://user-images.githubusercontent.com/786326/33987245-860ee424-e0c0-11e7-9f00-ee92839f002b.png">

Gör såhär istället:

(@anjabergman fyller i.)

**Comment by anjabergman** [comment]
Ändra rubriken till "Information" och gör den i samma färg som de andra. 

"Om du saknar en rättighet eller om någon av rättigheterna nedan är felaktig, vänligen kontakta katalogiseringsadmin för aktuellt sigel. Kontaktuppgifter till rätt administratör hittar du genom att **följa sigel-länken nedan** (Ändra till: klicka på länken för respektive sigel), eller genom att gå till listvyn för sigler (Gör till länk?) och där klicka på aktuellt sigel.

För övriga frågor, vänligen kontakta Libris kundservice på libris@kb.se.

**Comment by mblomdahl** [comment]
@anjabergman Fixing this in #132 release.

**Comment by mblomdahl** [comment]
@anjabergman @Hardesjo Plase verify on login.libris.kb.se.
