### ISSUE TITLE
Knappstorlek och knapptext

### ISSUE THREAD

**Issue by anjabergman** [libris/xl_auth#133]
Förstora knapparna i samma storlek som de andra knapparna och ändra copy i dom till "Lägg till ny användare", "Lägg till ny sigel"

<img width="1164" alt="likastorknappsomdeandra" src="https://user-images.githubusercontent.com/33147300/34036002-258bf7e4-e184-11e7-99d4-8184b709247d.png">
<img width="1203" alt="skarmavbild 2017-12-15 kl 10 36 37" src="https://user-images.githubusercontent.com/33147300/34036005-25ab3528-e184-11e7-959c-31a030ada349.png">

**Comment by mblomdahl** [comment]
@anjabergman Borde det vara "lägg till ny**tt** sigel" eller "lägg till ny sigel"?

**Comment by anjabergman** [comment]
Jag funderade med på det. Men nu har jag frågat både Harriet och Sara Lena och båda säger "ett sigel" och det låter ju mest normalt. Så kör på "Lägg till nytt sigel"

**Comment by mblomdahl** [comment]
@anjabergman Har snackat med Fredrik och Johan med, alla tycks vara rörande överens om att det är "ett" sigel. 😸
