### ISSUE TITLE
Rubrikändring

### ISSUE THREAD

**Issue by anjabergman** [libris/xl_auth#134]
Från: "Behörigheter på aktiva sigel" till "Mina behörigheter"

<img width="1154" alt="skarmavbild 2017-12-15 kl 10 54 12" src="https://user-images.githubusercontent.com/33147300/34036683-5b9d9ee4-e186-11e7-9034-eb4e301a63f7.png">

**Comment by mblomdahl** [comment]
@anjabergman Observera att denna listning visar inte *alla* dina behörigheter, utan det subset som avser aktiva sigel. Det kan vi förstås ändra. Jo, det borde vi nog... Jag gör en sån ändring för #132 så får vi se vad du tycker.
