### ISSUE TITLE
Hitta rätt snabbare i listor för Sigel och Användare (?)

### ISSUE THREAD

**Issue by anjabergman** [libris/xl_auth#136]
För att snabbare/lättare hitta rätt i listorna för Sigel och Användare: 
Kan vi implementera att när användaren trycker på en siffra/bokstav på tangentbordet, hamnar hen i ned i listan där den första siffran/bokstaven börjar för respektive Sigel/Användarnamn (Förnamn)? 

<img width="1200" alt="skarmavbild 2017-12-15 kl 11 26 22" src="https://user-images.githubusercontent.com/33147300/34037927-d118bf42-e18a-11e7-8754-df27213e2196.png">

<img width="1224" alt="skarmavbild 2017-12-15 kl 10 51 40" src="https://user-images.githubusercontent.com/33147300/34037685-0e214e96-e18a-11e7-86fc-460e47f29504.png">

**Comment by mblomdahl** [comment]
Customer feedback:

> Som katalogisatör för sigel Z tänker jag att det vore trevligt om man kunde sortera listan över alla aktiva sigler i bokstavsordning på namn och sigel, stigande *och* fallande.

**Comment by mxtthias** [comment]
Moved to Jira.
