### ISSUE TITLE
Lägg in länk till Libris katalogiseringstjänst

### ISSUE THREAD

**Issue by anjabergman** [libris/xl_auth#137]
<img width="1142" alt="skarmavbild 2017-12-15 kl 13 59 04" src="https://user-images.githubusercontent.com/33147300/34043177-22ad2a9a-e1a0-11e7-9b74-062eeeaf1081.png">

Efter att man loggat in vill man kanske navigera vidare till Libris Katalogisering, varpå vi kan lägga in en textrad i stil med: 
"Det här är din personliga profil-sida. Om du vill gå till Libris katalogiseringstjänst kan du göra det **här**."

Plus ta bort den feta stilen på texten 🥇

**Comment by mblomdahl** [comment]
@anjabergman Vad för URL ska vi sätta för Libris katalogiseringstjänst?

**Comment by mxtthias** [comment]
Vi väntar med att lägga till länken tills vi gått i produktion med XL.
