### ISSUE TITLE
copy på startsida (utloggad)

### ISSUE THREAD

**Issue by anjabergman** [libris/xl_auth#138]
Här behövs copyn ses över. Instruktioner om vadå?

<img width="1069" alt="skarmavbild 2017-12-19 kl 10 12 11" src="https://user-images.githubusercontent.com/33147300/34149427-4e1ab14a-e4a5-11e7-958b-fa880ed289e7.png">

**Comment by mblomdahl** [comment]
@anjabergman Vadan closed?

> Instruktioner om vadå?

Oklart.. Förändras löpande, varför det (historiskt sett) lämnats ospecifierat. Men så kommer ju inte vara fallet, framöver.

**Comment by anjabergman** [comment]
Nä förstår! därför jag assignade mig själv. Men tänkte bara fånga upp ändå.
