### ISSUE TITLE
Flytta upp "Dina behörigheter"

### ISSUE THREAD

**Issue by anjabergman** [libris/xl_auth#139]
Flytta upp modulen med "Dina behörigheter" Efter välkomstmodulen på Profilsidan. Eftersom den är den mest relevanta för användaren att se när de loggar in. Så kan "informationen om dina behörigheter" komma nedanför och "Ditt ansvar som katalogiseringsadmin" sist. 

Ordningen blir alltså:
Välkommen
Dina behörigheter
Information om dina behörigheter
Ditt ansvar som katalogiseringsadmin

**Comment by mxtthias** [comment]
@anjabergman Är det inte lätt att användarna missar information i boxarna om de ligger längst ner? Speciellt för användare som har många behörigheter finns det en risk att boxarna hamnar utanför skärmen.
