### ISSUE TITLE
Find out where to store Docker images

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#14]
Pull request #5 adds Docker builds in Jenkins as per project technology choices, "Docker integration for easy testing during ahead of first stable release".

But where do we publish it? Could we add a free organization-type account on [Docker Hub](https://hub.docker.com) and simply push it to `libris/xl_auth`?

**Comment by mxtthias** [comment]
Due to time constraints, this is down prioritized for now. There is a machine where we plan to run an internal Docker registry, but setting things up requires some coordination. So WONTFIX for now, but should hopefully be in place before the end of the year.
