### ISSUE TITLE
Copy för behörighetslistning i detaljvyn för ett sigel

### ISSUE THREAD

**Issue by anjabergman** [libris/xl_auth#141]
Från: "Behörigheter (Du ser enbart samtliga behörigheter för de sigel du är katalogiseringsadmin för.)"

Till: "Behörigheter (Du ser enbart **de behörigheter/behörigheterna** för de sigel du är katalogiseringsadmin för.)"

<img width="1196" alt="skarmavbild 2017-12-19 kl 10 41 30" src="https://user-images.githubusercontent.com/33147300/34150671-54e983e4-e4a9-11e7-9834-24a9c6cefecd.png">

**Comment by mblomdahl** [comment]
@anjabergman 

> Du ser enbart de behörigheter/behörigheterna för de sigel du är katalogiseringsadmin för.

Detta är felaktigt med utgångspunkt i den logik som är implementerad. Som katalogiseringsadmin ser man ett subset av behörigheterna när man inspekterar ett annat sigel; ett subset bestående av 1) behörigheter för användare som är katalogiseringsadmins för siglet och 2) egna behörigheter. Dock inte "vanliga" användares behörigheter, i.e. andra katalogisatörer och beståndsregistrerare. (Endast när man kollar på detaljvyn för ett sigel som man själv är kat.admin för ser man hela bilden.)

Detta skulle förstås kunna ändras till att man ser **alla** behörigheter när man kollar på ett annat sigel eller **inga**. Vad tänker du om detta?

**Comment by anjabergman** [comment]
Jag hajar inte riktigt problematiken. Vi kan låta det bero, och om det behövs ta en diskussion kring detta, nästa år!
