### ISSUE TITLE
Responsiveness issues due to new "Logout" label

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#170]
With the fix to #114 in #169 release, a new issue has emerged. This is how it looks like when having a medium long name and opening the page as cataloging admin:
![screen shot 2018-01-08 at 4 55 32 pm](https://user-images.githubusercontent.com/786326/34679760-3a9013de-f497-11e7-965d-10c5cb35a679.png)

@anjabergman @oBlissing What should happen with these buttons at this width? Before collapsing to a "sandwich" like this:
![screen shot 2018-01-08 at 5 16 10 pm](https://user-images.githubusercontent.com/786326/34679907-b54eaea0-f497-11e7-8141-ba2397056cf6.png)

**Comment by anjabergman** [comment]
Hjälper det om man dra ner på fontstorleken ngt? 👍 👎

**Comment by oBlissing** [comment]
Tror vi borde lösa det på något annat sätt än att dra ner fontsize. Jag fick för mig innan att vi bara visade förnamnet där uppe (av exakt detta skälet), men så verkar det inte.

Jag tycker man gör något av (eller kombinationer av alla):

* Dra ner spacing mellan meny-items
* Visa bara förnamnet
* Om namnet blir för långt, kapa av namnet och kör ellipsis "..."
* Ta bort gravataren (min baby nooooo 👿)

**Comment by mblomdahl** [comment]
@oBlissing @anjabergman Kolla gärna senaste ändringarna från #169 på https://login.libris.kb.se

Som det är löst nu så är onödig padding på vänstersidan av gravataren borttagen + så döljs texten  "Logga ut" när man kollar på en tablet-size skärm (`hidden-sm`), för sen i mobil-size:ade fönster löser hamburgaren problemet.

Betänk även att vi får gott om extra space när "beta" tas bort från produktnamnet. Såhär kommer de se ut då, i minsta läget innan hamburgaren:
![screen shot 2018-01-10 at 11 47 20 am](https://user-images.githubusercontent.com/786326/34768738-0e2c54e0-f5fc-11e7-89ec-e20e903073fb.png)

**Comment by anjabergman** [comment]
Det blir bra tycker jag! Och om vi för plats med "Logga ut" när betatexten försvinner utan problem, kan den ju bara läggas till igen. Annars låta det vara som det är nu. 👍
