### ISSUE TITLE
Fabric deployment of Nginx (sans cert)

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#177]
- [x] Add repo
- [x] Install nginx
- [x] Set SELinux httpd_can_network_connect=1
- [x] Add Nginx configs + restore correct SELinux contexts
- [x] Set nginx systemd service started and enabled
- [x] Open firewalld port 80 and 443

**Comment by mxtthias** [comment]
@mblomdahl With the latest addition to libris/devops, can we close this now?

**Comment by mblomdahl** [comment]
@mxtthias I think so, would be nice verifying that https.conf works too (provided we have a valid certificate), but I guess that will become part of "trying it out on a real stg server" next week.
