### ISSUE TITLE
Implement current production roll-out, but via Fabric instead of Ansible

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#178]
- [x] Start-up Postgres
- [x] Run `flask db upgrade`
- [x] Start-up xl_auth
- [x] Run `flask import_data` but **NOT** sending any emails at this point

**Comment by niklasl** [comment]
Via the devops-repo, correct? The point is to collect all deployment routines (and not to use Fabric per se).

**Comment by mxtthias** [comment]
@niklasl Yupyup. :)

**Comment by niklasl** [comment]
Of course, if it makes sense, app-specific deployment config can be bundled with the app; depending on which balance between uniform config and changability we need. (C.f. the recent "out of band" apache-config change needed for lxlviewer due to a move of the static folder.)
