### ISSUE TITLE
Collection codes should support renaming

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#26]
Add a special "change code" button to collections; one that does NOT actually change the code but instead, when attempting to change code from *A* to *E* ...

1) queries the database for all users that have privileges on *A*
2) displays a list to the user saying ...
    > Here's all the ones that will lose their privileges on code *A* and need to be manually added back on *E*:
    >
    > ID | Email | Katalogisera A | Beståndsregistrera A
    > -- | ----- | --------------- | ---------------------- 
    > 23 | simona@kb.se | yes | no
    > 29 | gunnar@kb.se | no | yes
    > 92 | pernilla@kb.se |yes | yes
    >
    > Are you absolutely 100 % sure that you want to proceed with the operation? 🙀  (y/n)
3) creates a new collection with code *E*, but all other properties same as initial collection *A* entry, except ...
    * `created_at=now()`
    * `replaces=['A']`
4) updates the old collection *A* by setting ...
    * `immutable=yes`
    * `replaced_by=['E']`
5) ~~updates the all the users from 1-2 by removing their privileges to *A*~~
6) executes steps ~~3-5~~ 3-4 in a single transaction

**Comment by mblomdahl** [comment]
Diagram with the life of a collection:
![170926_kb--life of collections model](https://user-images.githubusercontent.com/786326/30851665-9158f496-a2a9-11e7-9f3b-c0eaa25d17fd.png)
([170926_KB--Life of Collections Model.xml.zip](https://github.com/libris/xl_auth/files/1332405/170926_KB--Life.of.Collections.Model.xml.zip))

**Comment by mxtthias** [comment]
For 5. above, maybe it makes more sense to keep the users' privileges intact, but to mark A as inactive, or something like that? That way, it should be fairly easy to create a view for admins showing users with invalid privileges and also suggest potential edits ("I see here that user Foo has a privilege for A, which has been replaced by B, so you might want to update that").

As for the user interaction, you might want to run it by the UX people, but I think the general flow makes sense.

**Comment by mblomdahl** [comment]
@mxtthias Good idea! I updated the description + pasted in your comment as an addition to #27
