### ISSUE TITLE
Extend user edit view/model by assigning privileges to collections

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#27]
When editing a user, the form should support the following.

#### Listing + Removing Permissions

On the edit page, there should be a list with any existing permissions, e.g.

Code | Friendly Name | Category | Catalogize Permission | Beståndsregistrera Permission | Actions
---- | --------------- | --------- | ----------------------- | ------------------------------- | -----
A | Samling 1 | Bibliotek | yes | no | DELETE
B | Samling 2 | Kategori saknas | yes | yes | DELETE

Using the button in *Actions* column, privileges on a collection code can be revoked.

#### Adding new permissions to collection

1) selecting one collection code at a time from a drop-down menu
2) select privilege 'katalogisera' or 'beståndsregistrera'
3) press add

**Comment by mblomdahl** [comment]
From @mxtthias  comment on #26:

> /* snip */ it should be fairly easy to create a view for admins showing users with invalid privileges and also suggest potential edits ("I see here that user Foo has a privilege for A, which has been replaced by B, so you might want to update that").

Edit permissions view should take these outdated privileges into consideration.

Maybe the users with outdated privileges could be flagged somehow directly in the user listing as well.

**Comment by mxtthias** [comment]
:+1:
