### ISSUE TITLE
Collection codes should support splitting

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#28]
Add a special "split code" button for collections, to split e.g. code *E* into *Ea* and *Eb*. 

1) asks the operator to supply 2 new codes that *E* will be split into, whereas they enter "Ea" and "Eb"
2) queries the database for all users that have privileges on *E*
3) displays a list to the operator saying ...
    > Here's all the ones that will lose their privileges on what is currently on code *E* and need to be manually added back on *Ea* and *Eb*:
    >
    > ID | Email | Katalogisera E | Beståndsregistrera E
    > -- | ----- | --------------- | ---------------------- 
    > 23 | simona@kb.se | yes | no
    > 29 | gunnar@kb.se | no | yes
    > 92 | pernilla@kb.se |yes | yes
    >
    > Are you absolutely 100 % sure that you want to proceed with the operation?  (y/n)
4) creates two new collections with codes *Ea* and *Eb*, but all other properties same as initial collection *E* entry, except ...
    * `created_at=now()`
    * `replaces=['E']`
5) updates the old collection *E* by setting ...
    * `immutable=yes`
    * `replaced_by=['Ea', 'Eb']`
6) executes steps 4-5 in a single transaction

See illustration from "merge issue" #29:

![170927_kb--life of collections model](https://user-images.githubusercontent.com/786326/30909385-2ecf684a-a381-11e7-8496-7bdaa7c9cf64.png)

([170927_KB--Life of Collections Model.xml.zip](https://github.com/libris/xl_auth/files/1336719/170927_KB--Life.of.Collections.Model.xml.zip))

**Comment by kaipoykio** [comment]
Fanns visst specificationer för formatkonvertering. Vet dock inte hur väl vi förhåller oss till dessa !?


https://www.loc.gov/bibframe/mtbf/
