### ISSUE TITLE
Small command-line tool for extracting "sigels" from Voyager/SysAdmin (2 md)

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#38]
We need a simple command-line tool that can be used on KB network for querying the Voyager database about what "user-sigels" (huvudsigel) have permissions on what "sub-sigels/collections" (undersigel?)

The script write standard CSV data to stdout, in the following format:

Huvudsigel | Undersigel
------- | -------
S | HARK
S | SBr
S | SVtr
/* snip */ | /* snip */
T | Tdig
T | Tfb
/* snip */ | /* snip */

Example invocation

    read_voyager_sigels -h 10.127.10.2 -u VoyagerAdmin -p SuperSecret > 171013_voyager_dump.csv

**Comment by mblomdahl** [comment]
@kaipoykio Is this something you could assist with?

**Comment by kaipoykio** [comment]
oracle@ritchie:/profile_locations.sh

**Comment by mblomdahl** [comment]
Today's export: [171023_KB--sigel_locations.txt](https://github.com/libris/xl_auth/files/1406251/171023_KB--sigel_locations.txt)

**Comment by mblomdahl** [comment]
Today's export: [171025_KB--sigel_locations.txt](https://github.com/libris/xl_auth/files/1414385/171025_KB--sigel_locations.txt)

**Comment by mblomdahl** [comment]
Today's export: [171101_KB--sigel_locations.txt](https://github.com/libris/xl_auth/files/1434512/171101_KB--sigel_locations.txt)

**Comment by mblomdahl** [comment]
Today's export: [171102_KB--sigel_locations.txt](https://github.com/libris/xl_auth/files/1437869/171102_KB--sigel_locations.txt)

**Comment by mblomdahl** [comment]
Today's export: [171115_KB--sigel_locations.txt](https://github.com/libris/xl_auth/files/1474613/171115_KB--sigel_locations.txt)

**Comment by mblomdahl** [comment]
Today's export: 
[171129_KB--sigel_locations.txt](https://github.com/libris/xl_auth/files/1513982/171129_KB--sigel_locations.txt)
