### ISSUE TITLE
Small command-line tool for getting cataloguing manager email addresses from BibDB (1 md)

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#43]
We need a simple command-line tool that can be used for querying the BibDB database for a list of all "user-sigels" or "huvudsigel" and their associated cataloguing managers.

The script writes standard CSV data to stdout, in the following format:

Huvudsigel | Katalogiseringsansvarig
------- | -------
F | biblioteket@konstakademien.se
M | null
S | kb-katalogisering@listserv.kb.se
/* snip */ | /* snip */

Example invocation

    $ read_bibdb_cataloguing_managers -h https://bibdb.libris.kb.se --api-token SECRET > \
        171013_bibdb_dump.csv

**Comment by mblomdahl** [comment]
@kaipoykio Any chance you could help out with this? Needs it for requesting libraries to verify the permission we set for them are correct. And, as with #38, primary purpose is (again) being easily reusable as we cleanup/correct outdated BibDB records.

**Comment by kaipoykio** [comment]
Available through following api:

https://libris.kb.se/libinfo/library_konreg.jsp

**Comment by mblomdahl** [comment]
@kaipoykio I realized we need one more field in API output for cataloging managers; the full name!

Huvudsigel | Katalogiseringsansvarig | Namn
------- | ------- | -------
F | mats@kb.se | Mats Blomdahl
M | null | null
S | kb-katalogisering@listserv.kb.se | Kungl. Bibliotekets Katalogiseringsansvarig
/* snip */ | /* snip */ | /* snip */
