### ISSUE TITLE
Login page should have styling similar to how it should be (2 md)

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#6]
When entering `xl_auth` for the first time, styling should be similar to that of legacy [BibDB](https://bibdb-stg.libris.kb.se).

**Comment by mblomdahl** [comment]
@klngwll Is this "edit issue" button in the top right available to you? 
![screen shot 2017-09-12 at 9 11 09 am](https://user-images.githubusercontent.com/786326/30312570-6765ff0e-979a-11e7-9ce4-2f8a82e6263d.png)

**Comment by klngwll** [comment]
Styleguide http://kungbib.github.io/frontend-guide/

Github repo https://github.com/Kungbib/frontend-guide
