### ISSUE TITLE
Add OAuth2 Client model

### ISSUE THREAD

**Issue by mxtthias** [libris/xl_auth#65]
We need to be able to add/list/edit/delete applications that will use OAuth2 for authorization ("clients" in OAuth2 speak). See [0] for required fields.

* [x] Client model
* [x] Create view
* [x] List view
* [x] Edit view
* [x] Delete "view"

[0] https://flask-oauthlib.readthedocs.io/en/latest/oauth2.html

**Comment by mblomdahl** [comment]
@mxtthias The library doesn't seem too concerned with the `2` in `OAuth2` (default error endpoint is `/oauth/errors`, library name doesn't have a number in it and the "2" is only mentioned momentarily). Should we just refer to it as "OAuth" as well?

What do you think about adding a new "OAuth" button to the navbar, and keep clients, bearers, tokens and stuff in a flat `xl_auth.oauth` sub-package? Or what are you planning?

**Comment by mblomdahl** [comment]
@mxtthias Added this to *XL Integration* project.. What about the other issues here? Which would "naturally" be the next one after this?

**Comment by mxtthias** [comment]
The library can handle OAuth 1 as well, so I felt it made sense to be specific.

As for what's next, I'd say #66 or #67. Doesn't matter which, as long as both are done before #68.

**Comment by mblomdahl** [comment]
Great! So, how many days do you think this will take?

**Comment by mxtthias** [comment]
This issue? I'd guess 2-4 days, but it can be split up into smaller chunks. I've started looking into adding the model and the create and list views, which I guess should be 1-2 days work.
